# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 637c03fd70b54ed8e19ecb761dec352fc907b59c27a579d0fb953930d653110b31b45307464fe17f71e863f791d4adf657f7eaf93c8239df4d35f6fd197bf085

test:
  secret_key_base: c329e5a316f7a10da7fd736dbaedf7ccf2beb164805e30e71e1c895f44dbf648dd732ddc11a2f60217081c70a6480cbec9005a72431bbb0cf8014eb128f71ccb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
